parameters:
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  ChessableBanking\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  ChessableBanking\Infrastructure\Database\MySQL\Connection\MySQLConnection:
    $databaseHost: '%env(MYSQL_DB_HOST)%'
    $databasePort: '%env(MYSQL_DB_PORT)%'
    $databaseName: '%env(MYSQL_DATABASE)%'
    $userName: '%env(MYSQL_DB_USER)%'
    $password: '%env(MYSQL_DB_PASSWORD)%'
    $charset: 'utf8'

  ChessableBanking\Application\Migration\Registry\MigrationRegistry:
    calls:
      - method: registerMany
        arguments:
          $migrations:
            - '@ChessableBanking\Infrastructure\Country\Database\MySQL\Migration\CountryMigration'
            - '@ChessableBanking\Infrastructure\Location\Database\MySQL\Migration\LocationMigration'
            - '@ChessableBanking\Infrastructure\Branch\Database\MySQL\Migration\BranchMigration'
            - '@ChessableBanking\Infrastructure\Currency\Database\MySQL\Migration\CurrencyMigration'
            - '@ChessableBanking\Infrastructure\Customer\Database\MySQL\Migration\CustomerMigration'